### ISSUE TITLE
React Dom Issue

### ISSUE THREAD

**Issue by sanchit339** [sanchit339/CWH#1]
i am going through the codewithharry react tutorial and I am getting stuck in the problem of React router DOM which I am using to browse through the

**Comment by manish-107** [comment]
` <Router>
        <Navbar title="TextUtils" mode={mode} toggleMode={toggleMode} />
        <Alerts alert={alert} />

        <Routes>
          {/* <Route exact path="/about"> */}

          {/* </Route> */}
          {/* <Route exact path="/"> */}
          <Route exact path='/About' element={<About />} />
          <Route exact path='/' element={<TextForm showAlert={showAlert} heading="Enter the Text to Analyze" mode={mode} />} />

          {/* </Route> */}
        </Routes>
      </Router>` use this
